# Generated by Django 5.1.4 on 2025-01-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_auction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction',
            new_name='Listing',
        ),
    ]
