# Generated by Django 5.1.4 on 2025-01-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_owner_alter_listing_bidcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
