# Generated by Django 5.1.4 on 2025-01-12 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_bid_listing_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='leadingUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadingUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
